#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Example Script: TransUNet K-Fold Training Quick Demo

This script demonstrates how to use the TransUNet k-fold training implementation.
It shows the minimal code needed to run k-fold cross-validation.

This is an example for documentation purposes. Adjust paths to your actual data.

@author: ramad
"""

import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

def main():
    """
    Example workflow for TransUNet k-fold cross-validation.
    """
    
    print("="*70)
    print("TransUNet K-Fold Cross-Validation Example")
    print("="*70)
    
    # ========== Step 1: Import required modules ==========
    print("\n[Step 1] Importing modules...")
    
    try:
        import tensorflow as tf
        from train_kfold_wrapper import KFoldTrainer
        from transunet_model import build_transunet_mifocat, get_custom_objects
        print("✓ Imports successful")
    except ImportError as e:
        print(f"✗ Import failed: {e}")
        print("Please install requirements: pip install -r requirements.txt")
        return
    
    # ========== Step 2: Define paths ==========
    print("\n[Step 2] Defining paths...")
    
    # Adjust these paths to your actual data location
    DATA_DIR = "Data Test Resize 128 ED/"  # Directory with patient folders
    FOLD_METADATA = "kfold_metadata.json"   # Generated by split_data.py
    OUTPUT_DIR = "transunet_kfold_results"  # Where to save results
    
    print(f"  Data directory: {DATA_DIR}")
    print(f"  Fold metadata:  {FOLD_METADATA}")
    print(f"  Output directory: {OUTPUT_DIR}")
    
    # Check if paths exist
    data_path = Path(DATA_DIR)
    metadata_path = Path(FOLD_METADATA)
    
    if not data_path.exists():
        print(f"\n⚠ WARNING: Data directory not found: {DATA_DIR}")
        print("This is an example script. Please adjust DATA_DIR to your actual data location.")
        print("\nExpected directory structure:")
        print("  Data Test Resize 128 ED/")
        print("  ├── Pasien 001/")
        print("  │   ├── images/")
        print("  │   └── groundtruth/")
        print("  ├── Pasien 002/")
        print("  │   └── ...")
        print("  └── ...")
        return
    
    if not metadata_path.exists():
        print(f"\n⚠ WARNING: Fold metadata not found: {FOLD_METADATA}")
        print("Please run split_data.py first to generate k-fold splits:")
        print("\n  from split_data import CardiacDataSplitter")
        print("  splitter = CardiacDataSplitter(input_folder='...', output_folder='...')")
        print("  splitter.kfold_split(n_splits=5, val_ratio=0.1)")
        return
    
    # ========== Step 3: Initialize trainer ==========
    print("\n[Step 3] Initializing K-Fold trainer...")
    
    trainer = KFoldTrainer(
        fold_metadata_path=str(metadata_path),
        base_data_dir=str(data_path),
        output_dir=OUTPUT_DIR,
        seed=42
    )
    
    print("✓ Trainer initialized")
    
    # ========== Step 4: Run k-fold training ==========
    print("\n[Step 4] Starting k-fold cross-validation...")
    print("This will train TransUNet on all folds. This may take several hours.\n")
    
    # Training configuration
    config = {
        'model_type': 'transunet',      # Use TransUNet model
        'epochs': 50,                    # Max epochs per fold
        'batch_size': 32,                # Batch size
        'train_only': False,             # Also run test evaluation
        'start_fold': 0                  # Start from fold 0
    }
    
    print("Configuration:")
    for key, value in config.items():
        print(f"  {key}: {value}")
    
    # Run training
    try:
        results = trainer.run_all_folds(**config)
        
        print("\n" + "="*70)
        print("✓ K-Fold Cross-Validation Completed Successfully!")
        print("="*70)
        
        # Display results
        if results and 'val_loss_mean' in results:
            print(f"\nValidation Loss: {results['val_loss_mean']:.6f} ± {results.get('val_loss_std', 0):.6f}")
            if 'test_loss_mean' in results:
                print(f"Test Loss:       {results['test_loss_mean']:.6f} ± {results.get('test_loss_std', 0):.6f}")
            print(f"Folds Completed: {results.get('n_folds_completed', 0)}/{results.get('n_folds_total', 0)}")
        
        print(f"\nResults saved to: {OUTPUT_DIR}/")
        print("  - fold_results.json: Per-fold metrics")
        print("  - aggregated_results.json: Cross-fold statistics")
        print("  - fold_X/fold_X_best_model.h5: Best model checkpoints")
        
    except Exception as e:
        print(f"\n✗ Training failed: {e}")
        import traceback
        traceback.print_exc()
        return
    
    # ========== Step 5: Load and use trained model ==========
    print("\n[Step 5] Example: Loading a trained model...")
    
    fold_id = 0
    model_path = Path(OUTPUT_DIR) / f"fold_{fold_id}" / f"fold_{fold_id}_best_model.h5"
    
    if model_path.exists():
        try:
            from keras.models import load_model
            
            # Load model with custom objects
            custom_objs = get_custom_objects()
            model = load_model(str(model_path), custom_objects=custom_objs, compile=False)
            
            print(f"✓ Model loaded: {model.name}")
            print(f"  Parameters: {model.count_params():,}")
            print(f"  Input shape: {model.input_shape}")
            print(f"  Output shape: {model.output_shape}")
            
            print("\nYou can now use this model for prediction:")
            print("  predictions = model.predict(test_images)")
            
        except Exception as e:
            print(f"✗ Error loading model: {e}")
    
    print("\n" + "="*70)
    print("Example completed! See README_TRANSUNET_KFOLD.md for more details.")
    print("="*70)


if __name__ == '__main__':
    main()
